name: Docker

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Container Registry Docker Action
        uses: trentjones21/github-docker@master